"""
Export module for the FORGE tool.

This module handles writing analysis results to output files.
It generates a text report summarizing key metrics and warnings,
and exports a CSV file containing detailed product performance data.
"""

from pathlib import Path
from datetime import datetime


# -------------------------
# Report Output Directory
# -------------------------
# Define where report files will be saved.
REPORT_DIR = Path("reports")

# Ensure the reports directory exists before writing files
REPORT_DIR.mkdir(exist_ok=True)


def export_txt_report(results):
    """
    Export the analysis summary as a text report.

    Args:
        results (dict):
            Dictionary of summary metrics produced by the FORGE analysis module.

    Returns:
        None
    """

    # Create a timestamp so each report file has a unique name
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M")

    # Build the output file path
    file_path = REPORT_DIR / f"forge_report_{timestamp}.txt"

    # Open the report file for writing
    with open(file_path, "w") as f:

        # Write report title
        f.write("FORGE Analysis Report\n")
        f.write("----------------------\n\n")

        # Write the main metrics from the results dictionary
        for key, value in results.items():
            if key not in ["warnings", "recommendations"]:
                f.write(f"{key}: {value}\n")

        # -------------------------
        # Warning Messages
        # -------------------------
        # Include any risk warnings generated during analysis
        if results.get("warnings"):
            f.write("\nWarnings\n")
            f.write("--------\n")

            for warning in results["warnings"]:
                f.write(f"{warning}\n")

        # -------------------------
        # Executive Recommendations
        # -------------------------
        # Include strategy recommendations generated from the analysis
        if results.get("recommendations"):
            f.write("\nExecutive Recommendations\n")
            f.write("-------------------------\n")

            for rec in results["recommendations"]:
                f.write(f"- {rec}\n")

    # Notify the CLI that the report file was created successfully
    print(f"Report exported: {file_path}")


def export_csv_summary(product_performance):
    """
    Export product performance metrics as a CSV file.

    Args:
        product_performance (pandas.DataFrame):
            Aggregated product-level performance metrics generated by FORGE.

    Returns:
        None
    """

    # Create a timestamp so the CSV matches the report time
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M")

    # Build the output file path
    file_path = REPORT_DIR / f"product_summary_{timestamp}.csv"

    # Write the DataFrame to CSV
    product_performance.to_csv(file_path, index=False)

    # Notify the CLI that the export completed
    print(f"Product summary exported: {file_path}")
